### ISSUE TITLE
Replicated DIR fails to start

### ISSUE THREAD

**Issue by jflsakfja** [xtreemfs/xtreemfs#449]
New installation using http://download.opensuse.org/repositories/home:/xtreemfs/Debian_8.0/ on Debian 8.6

Setting up DIR replication following http://xtreemfs.org/xtfs-guide-1.5.1/index.html#tth_sEc6.3 results in this in the log for the DIR service:

[ I | PluginLoader         | main            |   1 | Sep 30 07:18:59 ] Loading plugin dependency /usr/share/java/Flease.jar.
Exception in thread "main" java.lang.NoSuchMethodError: org.xtreemfs.foundation.SSLOptions.<init>(Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;Ljava/io/Input
Stream;Ljava/lang/String;Ljava/lang/String;ZZLorg/xtreemfs/foundation/SSLOptions$TrustManager;)V
        at org.xtreemfs.babudb.config.ReplicationConfig.read(ReplicationConfig.java:237)
        at org.xtreemfs.babudb.config.ReplicationConfig.<init>(ReplicationConfig.java:143)
        at org.xtreemfs.babudb.replication.Main.start(Main.java:42)
        at org.xtreemfs.babudb.api.dev.plugin.PluginMain.execute(PluginMain.java:98)
        at org.xtreemfs.babudb.plugin.PluginLoader.<init>(PluginLoader.java:75)
        at org.xtreemfs.babudb.plugin.PluginLoader.init(PluginLoader.java:181)
        at org.xtreemfs.babudb.BabuDBFactory.createBabuDB(BabuDBFactory.java:96)
        at org.xtreemfs.dir.DIRRequestDispatcher.<init>(DIRRequestDispatcher.java:138)
        at org.xtreemfs.dir.DIR.main(DIR.java:58)

**Comment by jflsakfja** [comment]
Forgot to add that DIR replication is SSL enabled (of course, that's what the error is about :-))

**Comment by robert-schmidtke** [comment]
@jflsakfja please close the issue if you think it's resolved, adding any necessary comments. otherwise please feel free to ask for hints and advice.

**Comment by jflsakfja** [comment]
The issue still exists, DIR service fails to start with the error shown in the first reply. As far as I can tell it's an error related to SSL, but SSL was set up according to the guides shown.

**Comment by robert-schmidtke** [comment]
Which XtreemFS version are you using? Have you made sure the plugin configuration points to the correct jar file? Turning on debug level logging might help identify the issue.

**Comment by jflsakfja** [comment]
XtreemFS v1.5.1

Haven't touched any setting related to jar files, but here they are:
(server-repl-plugin/dir.properties)
plugin.jar = /usr/share/java/BabuDB_replication_plugin.jar
babudb.repl.dependency.0 = /usr/share/java/Flease.jar

Turning on debug logging stops at the exact same error as before:
#             database dir: /var/lib/xtreemfs/dir/database/
#         database log dir: /var/lib/xtreemfs/dir/db-log/
#                sync mode: FDATASYNC
#     pseudo sync interval: 200
#        max. queue length: 250
#             num. threads: 0
#   checkpointing interval: 300
#       max. log file size: 16777216
#   num. records per block: 64
#     max. block file size: 536870912
#      compression enabled: false
#            mmap disabled: false
#               mmap limit: -1
#               plugin-0: /etc/xos/xtreemfs/server-repl-plugin/dir.properties

[ I | PluginLoader         | main            |   1 | Sep 30 13:17:03 ] Loading plugin dependency /usr/share/java/Flease.jar.
Exception in thread "main" java.lang.NoSuchMethodError: org.xtreemfs.foundation.SSLOptions.<init>(Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;Ljava/io/Input
Stream;Ljava/lang/String;Ljava/lang/String;ZZLorg/xtreemfs/foundation/SSLOptions$TrustManager;)V
        at org.xtreemfs.babudb.config.ReplicationConfig.read(ReplicationConfig.java:237)
        at org.xtreemfs.babudb.config.ReplicationConfig.<init>(ReplicationConfig.java:143)
        at org.xtreemfs.babudb.replication.Main.start(Main.java:42)
        at org.xtreemfs.babudb.api.dev.plugin.PluginMain.execute(PluginMain.java:98)
        at org.xtreemfs.babudb.plugin.PluginLoader.<init>(PluginLoader.java:75)
        at org.xtreemfs.babudb.plugin.PluginLoader.init(PluginLoader.java:181)
        at org.xtreemfs.babudb.BabuDBFactory.createBabuDB(BabuDBFactory.java:96)
        at org.xtreemfs.dir.DIRRequestDispatcher.<init>(DIRRequestDispatcher.java:138)
        at org.xtreemfs.dir.DIR.main(DIR.java:58)

**Comment by robert-schmidtke** [comment]
I think this might have to do with an outdated flease version and we fixed it in the unstable packages. Could you give the [unstable packages](http://download.opensuse.org/repositories/home:/xtreemfs:/unstable/) a shot? Be sure to completely uninstall the stable version first.

Please also note that DIR and MRC replication is experimental and not ready for production use. We are aware of issues during failover of a DIR/MRC that would prevent the system from working as expected.

**Comment by jflsakfja** [comment]
Tried the unstable packages and it does indeed fix it :-)

Thank you
